import Head from 'next/head';
import { Box, Grid, Typography, useMediaQuery, useTheme } from '@mui/material';
import ArticleCard from '@/components/global/ArticleCard';
import { mockArticles } from '@/data/mockData';

export default function Home() {
  const theme = useTheme();
  const colors = theme.palette;
  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));

  return (
    <>
      <Head>
        <title>Inkwell - a modern blog site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>{`
          body {
            background-image: url(${mockArticles[0].contentImage});
            background-size: cover;
            background-position: center;
          }
        `}</style>
      </Head>

      <Box
        sx={{
          m: isMobile ? 2 : 10,
          p: 2,
          backgroundColor: colors.background.default,
          borderRadius: 2
        }}
      >
        <Box sx={{ pb: 2, display: 'flex', justifyContent: 'center' }}>
          <Typography variant={isMobile ? 'h3' : 'h1'} fontWeight={400}>
            Articles
          </Typography>
        </Box>

        <Box sx={{ display: 'flex', justifyContent: 'center' }}>
          <Grid container spacing={2}>
            <Grid item xs={8}>
              <ArticleCard
                id={mockArticles[0].id}
                contentImage={mockArticles[0].contentImage}
                category={mockArticles[0].category}
                title={mockArticles[0].title}
                author={mockArticles[0].author}
                authorImage={mockArticles[0].authorImage}
                height={476}
              />
            </Grid>
            <Grid item xs={4}>
              <Grid container spacing={2} direction="column">
                <Grid item xs={6}>
                  <ArticleCard
                    id={mockArticles[2].id}
                    contentImage={mockArticles[2].contentImage}
                    category={mockArticles[2].category}
                    title={mockArticles[2].title}
                    author={mockArticles[2].author}
                    authorImage={mockArticles[2].authorImage}
                    height={230}
                    isSmall
                  />
                </Grid>
                <Grid item xs={6}>
                  <ArticleCard
                    id={mockArticles[3].id}
                    contentImage={mockArticles[3].contentImage}
                    category={mockArticles[3].category}
                    title={mockArticles[3].title}
                    author={mockArticles[3].author}
                    authorImage={mockArticles[3].authorImage}
                    height={230}
                    isSmall
                  />
                </Grid>
              </Grid>
            </Grid>
          </Grid>
        </Box>
      </Box>
    </>
  );
}
