import Head from 'next/head';
import { Box } from '@mui/system';
// import Dashboard from './main/dashboard';

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Template App</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Box>{/* <Dashboard /> */}</Box>
    </Box>
  );
}
